modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "ARR"

[[mods]]
modId = "pmegundamuniverse"
version = "${version}"
displayName = "Pomkots Mechs - Gundam Universe"
authors = "grc_mcs"
description = '''
Addon that introduces Gundam mechs to Pomkots Mechs.
'''
logoFile = "assets/pmegundamuniverse/icon.png"

[[dependencies.pmegundamuniverse]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pmegundamuniverse]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pmegundamuniverse]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.pmegundamuniverse]]
modId = "geckolib"
mandatory = true
versionRange = "[4.4.9,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.pmegundamuniverse]]
modId = "leawind_third_person"
mandatory = true
versionRange = "[2.1.0,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.pmegundamuniverse]]
modId = "pomkotsmechsextension"
mandatory = true
versionRange = "[0.0.1-alpha.4,)"
ordering = "AFTER"
side = "CLIENT"
