plugins {
    id 'net.minecraftforge.gradle' version '6.0.+' 
    id 'com.github.johnrengelman.shadow'
    id 'maven-publish'
}

base {
    archivesName = "${rootProject.archives_name}-${project.name}"
}

minecraft {
    mappings channel: 'official', version: rootProject.minecraft_version
}

configurations {
    // Files in this configuration will be bundled into your mod using the Shadow plugin.
    // Don't use the `shadow` configuration from the plugin itself as it's meant for excluding files.
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

repositories {
    flatDir {
        dirs 'libs'  // プロジェクト内のlibsフォルダを指定
    }

    maven { url "https://maven.shedaniel.me/" }
    maven { url "https://maven.architectury.dev/" }
    maven {
        name = 'GeckoLib'
        url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
        content {
            includeGroupByRegex("software\\.bernie.*")
            includeGroup("com.eliotlash.mclib")
        }
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${rootProject.forge_version}"

    implementation fg.deobf("software.bernie.geckolib:geckolib-forge-${rootProject.minecraft_version}:${rootProject.geckolib_version}")
    implementation fg.deobf("com.eliotlash.mclib:mclib:20")
    implementation files('libs/pomkotsmechs-forge-0.0.1-alpha.4-dev-shadow.jar')
    implementation fg.deobf("me.shedaniel.cloth:cloth-config-forge:${rootProject.cloth_config_version}")
    implementation fg.deobf("dev.architectury:architectury-forge:${rootProject.architectury_version}")
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

// Ensure sources compile consistently across platforms with UTF-8 encoding
tasks.withType(JavaCompile).configureEach {
    options.release = 17
    options.encoding = 'UTF-8'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = base.archivesName.get()
            from components.java
        }
    }

    repositories {
        // Add repositories to publish to here if needed.
    }
}

processResources {
    inputs.property 'version', project.version

    filesMatching('META-INF/mods.toml') {
        expand version: project.version
    }
}

// Configure the shaded jar and reobfuscation
shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier.set('')
    finalizedBy 'reobfShadowJar'
}

reobf {
    shadowJar {}
}

tasks.build.dependsOn 'reobfShadowJar'

